export const HEX_COLOR_SUCCESS = 0x00ff00;
export const HEX_COLOR_WARNING = 0xffff00;
export const HEX_COLOR_DANGER = 0xff0000;
export const HEX_COLOR_WHITE = 0xffffff;
export const HEX_COLOR_GREY = 0x808080;
export const HEX_COLOR_LIGHT_GREY = 0x333333;
export const HEX_COLOR_PRIMARY = 0x4e342e;
export const HEX_COLOR_LIGHT = 0x7b5e57;
export const HEX_COLOR_DARK = 0x260e04;
export const HEX_COLOR_RED_AWARENESS = 0xb22222;
export const HEX_COLOR_GREEN_FINESSE = 0x228b22;
export const HEX_COLOR_RESILIENCE = 0x1e3a5f;
export const HEX_COLOR_THOUGHTFULNESS = 0xb8860b;
export const HEX_COLOR_RED_AWARENESS_DARK = 0x800000;
export const HEX_COLOR_GREEN_FINESSE_DARK = 0x006400;
export const HEX_COLOR_RESILIENCE_DARK = 0x0b2349;
export const HEX_COLOR_THOUGHTFULNESS_DARK = 0x5a4500;
export const HEX_COLOR_RED_AWARENESS_DARKER = 0x4d0000; // Even darker shade of red
export const HEX_COLOR_GREEN_FINESSE_DARKER = 0x003200; // Even darker shade of green
export const HEX_COLOR_RESILIENCE_DARKER = 0x050e24; // Even darker shade of blue
export const HEX_COLOR_THOUGHTFULNESS_DARKER = 0x2d2200; // Even darker shade of brown/goldenrod
export const COLOR_SUCCESS = "#00ff00";
export const COLOR_WARNING = "#ffff00";
export const COLOR_DANGER = "#ff0000";
export const COLOR_WHITE = "#ffffff";
export const COLOR_GREY = "#808080";
export const COLOR_LIGHT_GREY = "#333333";
export const COLOR_PRIMARY = "#4e342e";
export const COLOR_LIGHT = "#7b5e57";
export const COLOR_DARK = "#260e04";
export const COLOR_RED_STRENGTH = "#B22222";
export const COLOR_GREEN_AGILITY = "#228B22";
export const COLOR_BLUE_INTELLIGENCE = "#1E3A5F";
export const COLOR_YELLOW_MISCELLANEOUS = "#B8860B";
export const COLOR_RED_AWARENESS_DARK = "#800000";
export const COLOR_GREEN_FINESSE_DARK = "#006400";
export const COLOR_RESILIENCE_DARK = "#0B2349";
export const COLOR_THOUGHTFULNESS_DARK = "#5A4500";
export const COLOR_RED_AWARENESS_DARKER = "#4D0000"; // Even darker shade of red
export const COLOR_GREEN_FINESSE_DARKER = "#003200"; // Even darker shade of green
export const COLOR_RESILIENCE_DARKER = "#050E24"; // Even darker shade of blue
export const COLOR_THOUGHTFULNESS_DARKER = "#2D2200"; // Even darker shade of brown/goldenrod
